export const products = {
    '46bri': {
        id: '46bri',
        manufacturer: "Brioni",
        description: "Brioni red hearted sunglasses",
        color: ["red"],
        price: 400,
        imageURL: "https://i.ibb.co/1n9YN9p/burlesque-ga37fa2390-1920.jpg",
    },
    '47bri': {
        id: '47bri',
        manufacturer: "Brioni",
        description: "Brioni green brown transparent with acetate and titanium",
        color: ["green", "brown"],
        price: 360,
        imageURL: "https://i.ibb.co/cJL8frB/caleb-lucas-6r-Ru-Aqt-Wt60-unsplash.jpg",
    },
    '48bri': {
        id: '48bri',
        manufacturer: "Brioni",
        description: "Brioni square sunglasses made with acetate and titanium",
        color: ["black"],
        price: 490,
        imageURL: "https://i.ibb.co/C0Bqh9c/woman-gc313e4feb-1920.jpg",
    },
    '49bri': {
        id: '49bri',
        manufacturer: "Brioni",
        description: "Brioni square yellow hippie sunglasses",
        color: ["yellow"],
        price: 320,
        imageURL: "https://i.ibb.co/8PWgM9M/luigi-estuye-lucreative-Nb-QBf-C6-Dfw-unsplash.jpg",
    },
    '50bri': {
        id: '50bri',
        manufacturer: "Brioni",
        description: "Brioni rounded sunglasses made with acetate and titanium",
        color: ["black"],
        price: 490,
        imageURL: "https://i.ibb.co/5M4dmx4/glasses-g4db330591-1920.jpg",
    },
    '51bri': {
        id: '51bri',
        manufacturer: "Brioni",
        description: "Brioni cat eye sunglasses",
        color: ["silver"],
        price: 360,
        imageURL: "https://i.ibb.co/WPX88SG/woman-gd5276871d-1920.jpg",
    },
    '52bri': {
        id: '52bri',
        manufacturer: "Brioni",
        description: "Brioni dark rectangular sunglasses",
        color: ["brown"],
        price: 420,
        imageURL: "https://i.ibb.co/L550bcD/scorpio-creative-FRGznnxm-LRA-unsplash.jpg",
    },
    '53bri': {
        id: '53bri',
        manufacturer: "Brioni",
        description: "Brioni pilot light havana sunglasses",
        color: ["silver"],
        price: 320,
        imageURL: "https://i.ibb.co/6Dk7CGh/woman-ga29a8ad14-1920.jpg",
    },
    '54bri': {
        id: '54bri',
        manufacturer: "Brioni",
        description: "Brioni rectangular oversize havana acetate sunglasses",
        color: ["black"],
        price: 320,
        imageURL: "https://i.ibb.co/9cLNx7q/jonathan-borba-reiw-Bh-NJQS0-unsplash.jpg",
    },
    '55bri': {
        id: '55bri',
        manufacturer: "Brioni",
        description: "Brioni rectangular brown and green sunglasses",
        color: ["brown", "green"],
        price: 320,
        imageURL: "https://i.ibb.co/PTxq0xs/sunset-g5519dda2a-1920.jpg",
    },
    '56bri': {
        id: '56bri',
        manufacturer: "Brioni",
        description: "Brioni squared vintage look black acetate sunglasses",
        color: ["black"],
        price: 350,
        imageURL: "https://i.ibb.co/m8qf0cY/model-gcecd4b72f-1920.jpg",
    },
    '57bri': {
        id: '57bri',
        manufacturer: "Brioni",
        description: "Brioni vintage inspired black transparent sunglasses",
        color: ["black"],
        price: 360,
        imageURL: "https://i.ibb.co/bLkM1pm/mubariz-mehdizadeh-Py8-F6-h-Rn5o-unsplash.jpg",
    },
    '58bri': {
        id: '58bri',
        manufacturer: "Brioni",
        description: "Brioni titanium silver grey sunglasses",
        color: ["silver", "grey"],
        price: 460,
        imageURL: "https://i.ibb.co/5MwNs59/prince-akachi-4-Yv84-Vg-Qk-RM-unsplash.jpg",
    },
    '59bri': {
        id: '59bri',
        manufacturer: "Brioni",
        description: "Brioni titanium silver green sunglasses sunglasses",
        color: ["green", "silver"],
        price: 460,
        imageURL: "https://i.ibb.co/FDcgMNH/woman-ga205e16f2-1920.jpg",
    },
    '60bri': {
        id: '60bri',
        manufacturer: "Brioni",
        description: "Brioni vintage inspired black sunglasses",
        color: ["black"],
        price: 320,
        imageURL: "https://i.ibb.co/7kFsCbW/alex-iby-Xh-MSz5-I1kn8-unsplash.jpg",
    },

}

